
spring:
  application:
    name: java2019
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.132.146.171:3306/java2019
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 2019

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

